### ISSUE TITLE
React Nativeでの利用

### ISSUE THREAD

**Issue by HiromuTsuchiya** [seibii/shaken-qr-reader#348]
こちらのライブラリはReact Nativeでも利用可能でしょうか？

現在React Nativeで作成中のアプリで車の車検証を読み込みたいと思っており、
利用可能かお聞きしたいと考えております。
よろしくお願いいたします。

**Comment by amatotsuji** [comment]
@HiromuTsuchiya 

Seibiiでは
- モバイルアプリでこのライブラリは使用していない
- ReactNativeでもこのライブラリは使用していない

ため動作確認はしていません。

以上の前提で見解を示しますと、使える可能性がありそうですが我々が見えていないところで問題があるかもしれません。

詳細は下記の通りです。
- React nativeでnpm packageは利用可能な模様
  - https://stackoverflow.com/questions/32293050/using-npm-modules-in-react-native-projects
- このライブラリではカメラまわりのAPIは使っていないので呼び出し側でカメラまわりは実装する必要がある
  - ImageData を呼び出し側からもらいQRコードを解析している
- QRの解析は jsQR に依存しているので、それがReactNativeに対応していなければこのライブラリも使用不可

最後に、PullRequest自体は歓迎しています。
